services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fundraising-backend
    ports:
      - "1609:1609"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
